mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.yqbd.model
  configLocation: classpath:mybatis/mybatis-config.xml

aes:
  iv: unforethoughtful
  key: perineorrhaphies