spring:
  email-enabled: false
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6o01k9ajdh1s9zs2o.mysql.rds.aliyuncs.com:3306/yqbd?useUnicode=true&characterEncoding=UTF8
    username: root
    password: YRJeunie!((^0909
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false
  devtools:
    restart:
      exclude: static/**, templates/**